### ISSUE TITLE
https://i.pximg.net/ 返回403

### ISSUE THREAD

**Issue by beefjerky331** [yuban10703/SetuAPI#2]
Pixiv现在的图片服务器均配备了防盗链，访问时会验证来源(referrer)信息，前端无找到方法破解，无解
但是可以用后端代理访问，代理时追加referrer值以伪造来源绕过验证。
json数据文件里的域名全部都可以改成https://i.pixiv.cat/*
这是我改好的文件↓
https://www.lanzouw.com/iGC8rxnvi9e
密码:ctta

**Comment by yuban10703** [comment]
下次加个选项支持换自定义的域名
   X﹏X

**Comment by beefjerky331** [comment]
> 

好咧！

**Comment by yuban10703** [comment]
已增加replace_url字段

**Comment by beefjerky331** [comment]
> 已增加replace_url字段

哟西
