### ISSUE TITLE
你这json是特殊格式的吗?

### ISSUE THREAD

**Issue by lancer-wang** [yuban10703/SetuAPI#3]
我前面后面加了[],中间加了,才能正确识别....

**Comment by yuban10703** [comment]
> 我前面后面加了[],中间加了,才能正确识别....

这是MongoDB直接导出来的json..

**Comment by lancer-wang** [comment]
> > 我前面后面加了[],中间加了,才能正确识别....
> 
> 这是MongoDB直接导出来的json..

可能是mongodb比较特殊吧..
![image](https://user-images.githubusercontent.com/69783837/154422977-81c1e61d-3fac-4b03-a3b8-6abc51b17dd1.png)
这个是我自己手动加的,不加都读取不了

**Comment by yuban10703** [comment]
> > > 我前面后面加了[],中间加了,才能正确识别....
> > 
> > 这是MongoDB直接导出来的json..
> 
> 可能是mongodb比较特殊吧..
> ![image](https://user-images.githubusercontent.com/69783837/154422977-81c1e61d-3fac-4b03-a3b8-6abc51b17dd1.png)
> 这个是我自己手动加的,不加都读取不了

可以试试一行一行读

**Comment by lancer-wang** [comment]
> > > > 我前面后面加了[],中间加了,才能正确识别....
> > > 
> > > 
> > > 这是MongoDB直接导出来的json..
> > 
> > 
> > 可能是mongodb比较特殊吧..
> > ![image](https://user-images.githubusercontent.com/69783837/154422977-81c1e61d-3fac-4b03-a3b8-6abc51b17dd1.png)
> > 这个是我自己手动加的,不加都读取不了
> 
> 可以试试一行一行读

我试过一行一行,一行就是全部,我也不知道为什么
