### ISSUE TITLE
服务器挂了？

### ISSUE THREAD

**Issue by DullJZ** [yuban10703/SetuAPI#4]
访问api出现
![image](https://user-images.githubusercontent.com/79080562/178992781-fda5fc5d-b4fa-4f0b-b8a3-c2d5fe21b95a.png)

**Comment by yuban10703** [comment]
服务器搭梯子被腾讯封了,重建ing......

**Comment by DullJZ** [comment]
好的。能略微写下搭建api的步骤吗，我写的[telegram bot](https://github.com/DullJZ/SetuBot)调用的你的api，还是希望能用自己的服务，访问量大了也不会影响到你

**Comment by yuban10703** [comment]
可以白嫖https://cloud.mongodb.com/的数据库
然后想办法把json导进去,数据库和表的名字可以在docker的环境变量里设置

**Comment by yuban10703** [comment]
应该恢复了
